### ISSUE TITLE
Necessary to develop  API support transaction based on block hash  - transaction hash. 

### ISSUE THREAD

**Issue by cmcm2222** [dahemmer/sebak-explorer#1]
Hello. @dahemmer. 
I'm Aiden working in BOScoin. 
I got some request from Kucoin that please support API which is  `https://sebak-explorer.herokuapp.com/transactions/{blockId}-{transactionId} `.

**Comment by dahemmer** [comment]
Hello @cmcm2222. Could you please elaborate on the information that has to be displayed for this endpoint? Should the block information along with its transactions be displayed?

The explorer currently provides the `/transactions/{transaction_hash}` endpoint which shows all transaction information, along with its operations. The block information could also be shown in this endpoint.
The `/blocks/{block_hash}` and `/blocks/{height}` endpoint is also available, but it only shows the block information for now. In the near future, all transactions for a given block will also be displayed.

Some examples:
* https://sebak-explorer.herokuapp.com/transactions/EnH8fNibdswNEPHE83rfH3Ge2tebPtyMGhq8yhQua3K
* https://sebak-explorer.herokuapp.com/blocks/9RvTGVQwb2Ax1Q9E6ZujqGzhJVWBQoyoEqASdV1wjxZp 
* https://sebak-explorer.herokuapp.com/blocks/106343

Would the information behind these endpoints be sufficient?

**Comment by dahemmer** [comment]
The requested endpoint has been implemented as `/operations/{operation_hash}` and displays all information about the operation for the given operation_hash.

Example: https://sebak-explorer.netlify.com/operations/4DPBDEyRYn9rqpaG7ZCaLTdrAUQ4kV82BEDXAEVjT1qR-5GHrXFuJ9AjLNdJtKjExw66zG73V6EnwhVX8W1xgPtwB
